# Generated by Django 2.1 on 2018-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0091_merge_20180825_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date_time',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='local_body',
            field=models.TextField(default='', max_length=250),
        ),
    ]
