# Generated by Django 2.1 on 2018-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0092_auto_20180828_1429'),
        ('mainapp', '0092_auto_20180828_1407'),
    ]

    operations = [
    ]
