# Generated by Django 2.1 on 2018-08-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0093_merge_20180828_1750'),
        ('mainapp', '0092_auto_20180828_1428'),
    ]

    operations = [
    ]
