# Generated by Django 2.1 on 2018-08-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0093_auto_20180827_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
